## Applying simple Neural Network model on Iris Data

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris= load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X=iris.data
#X

In [7]:
y=iris.target

In [8]:
#class 0 ---> [1,0,0]
#class 1 ---> [0,1,0]
#class 2 ---> [0,0,1]
# to do this we are using Keras
from keras.utils import to_categorical


Using TensorFlow backend.


In [9]:
y=to_categorical(y)

In [10]:
print(y.shape)

(150, 3)


In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.33, random_state=42)

In [13]:
from sklearn.preprocessing import MinMaxScaler # to scale value between 0 and 1

In [14]:
scaler_object=MinMaxScaler()

In [15]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [16]:
scaled_X_train=scaler_object.transform(X_train)

In [17]:
scaled_X_test=scaler_object.transform(X_test)

In [18]:
 #scaled_X_train

In [19]:
# Building the network using keras 
from keras.models import Sequential # to get sequesces
from keras.layers import Dense # to make dense model i.e., no. of hidden layer greater than 2(simply saying)

In [20]:
model= Sequential() #to creat Sequestial model
# to add layer to model (in this case Dense layer)
model.add(Dense(8,input_dim=4,activation='relu')) # taking '8 neuron' and input dimention 4=no. of features
model.add(Dense(8,input_dim=4,activation='relu')) # adding one more same layer as above
model.add(Dense(3,activation='softmax')) # taking '3 neuron' same as in outpur layer and using softmax here
#output should be close to [.2,.3,.5] A per value of y

# Now compiling it
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [21]:
# to get summary of model
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________
None


In [22]:
model.fit(scaled_X_train, y_train, epochs=150, verbose =2)
# verbose is just how much output infomation we want ex- verbose=0 give no information
#while verbose=2 with give information of accuracy

Epoch 1/150
 - 0s - loss: 1.0663 - accuracy: 0.4300
Epoch 2/150
 - 0s - loss: 1.0627 - accuracy: 0.4700
Epoch 3/150
 - 0s - loss: 1.0605 - accuracy: 0.5400
Epoch 4/150
 - 0s - loss: 1.0580 - accuracy: 0.5500
Epoch 5/150
 - 0s - loss: 1.0551 - accuracy: 0.5900
Epoch 6/150
 - 0s - loss: 1.0524 - accuracy: 0.6000
Epoch 7/150
 - 0s - loss: 1.0492 - accuracy: 0.6200
Epoch 8/150
 - 0s - loss: 1.0459 - accuracy: 0.6200
Epoch 9/150
 - 0s - loss: 1.0424 - accuracy: 0.6300
Epoch 10/150
 - 0s - loss: 1.0385 - accuracy: 0.6400
Epoch 11/150
 - 0s - loss: 1.0344 - accuracy: 0.6400
Epoch 12/150
 - 0s - loss: 1.0298 - accuracy: 0.6400
Epoch 13/150
 - 0s - loss: 1.0250 - accuracy: 0.6400
Epoch 14/150
 - 0s - loss: 1.0194 - accuracy: 0.6500
Epoch 15/150
 - 0s - loss: 1.0138 - accuracy: 0.6500
Epoch 16/150
 - 0s - loss: 1.0075 - accuracy: 0.6500
Epoch 17/150
 - 0s - loss: 1.0012 - accuracy: 0.6500
Epoch 18/150
 - 0s - loss: 0.9943 - accuracy: 0.6500
Epoch 19/150
 - 0s - loss: 0.9873 - accuracy: 0.6500
Ep

In [23]:
model.predict(scaled_X_test) # it gives us probability of predict for each 3 output
#the highest probability we assume as answer

array([[2.5688091e-02, 5.0645924e-01, 4.6785265e-01],
       [9.7962373e-01, 1.5936112e-02, 4.4402503e-03],
       [7.7803869e-04, 2.2857371e-01, 7.7064824e-01],
       [2.5924420e-02, 4.9254665e-01, 4.8152897e-01],
       [8.6990995e-03, 4.0247923e-01, 5.8882165e-01],
       [9.4875503e-01, 3.9873812e-02, 1.1371181e-02],
       [8.5793003e-02, 5.5285674e-01, 3.6135021e-01],
       [3.3417202e-03, 2.9499444e-01, 7.0166385e-01],
       [8.1736222e-03, 3.7971035e-01, 6.1211598e-01],
       [4.4469990e-02, 5.3973907e-01, 4.1579092e-01],
       [9.4000995e-03, 3.9128685e-01, 5.9931296e-01],
       [9.5781088e-01, 3.3991877e-02, 8.1972983e-03],
       [9.7391123e-01, 2.0467613e-02, 5.6211432e-03],
       [9.6280479e-01, 2.9905524e-02, 7.2897612e-03],
       [9.8804224e-01, 9.8043904e-03, 2.1532695e-03],
       [2.8506955e-02, 4.9053049e-01, 4.8096254e-01],
       [3.8371952e-03, 3.1807563e-01, 6.7808723e-01],
       [4.6827231e-02, 5.4765433e-01, 4.0551838e-01],
       [3.9486773e-02, 5.360

In [24]:
print(y_test.shape)
print(scaled_X_test.shape)

(50, 3)
(50, 4)


In [25]:
# to predict classes
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)

In [26]:
print(y_test[0:5,:]) 

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [27]:
# here y_test and prediction value is in different formet so we need to make them in same formate
predictions=model.predict_classes(scaled_X_test)
y_test.argmax(axis=1) #this different from y_test in case of format

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [28]:
# now comparing predictions with y_test.argmax(axis=1)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
confusion_matrix(y_test.argmax(axis=1),predictions) # rows are actual and column are predicted value for each classes

array([[19,  0,  0],
       [ 0, 10,  5],
       [ 0,  0, 16]], dtype=int64)

In [29]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.67      0.80        15
           2       0.76      1.00      0.86        16

    accuracy                           0.90        50
   macro avg       0.92      0.89      0.89        50
weighted avg       0.92      0.90      0.90        50



In [30]:
print(accuracy_score(y_test.argmax(axis=1),predictions))

0.9


In [31]:
# Now to save this this model
#model.save('...filelocation/filename.h5')
model.save('E:/study material/Deep learning/neural network/IrisDataNN.h5')

In [32]:
# to open this save model
from keras.models import load_model
new_model=load_model('E:/study material/Deep learning/neural network/IrisDataNN.h5')

In [33]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)